name: Test & Deploy

on:
  push:
    branches:
    - master
    - release/*

jobs:
  master-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn run build
    - run: yarn test

  firebase-deploy:
    runs-on: ubuntu-latest
    needs: [master-review]

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn run build --if-present
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
